backend:
  name: github
  repo: prissycorrea/daniloreis-cv
  branch: main
  site_domain: cvdaniloreis.netlify.app
  base_url: daniloreiscv-qbhz7n8nb-prissycorreas-projects.vercel.app

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "sobre"
    label: "Sobre Danilo"
    files:
      - label: "Cabeçalho"
        name: "sobre"
        file: "conteudo/sobre.md"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Subtítulo", name: "subtitle", widget: "string" }
          - { label: "Descrição", name: "body", widget: "markdown" }

  - name: "formacoes"
    label: "Formação Profissional"
    folder: "conteudo/formacoes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Curso", name: "curso", widget: "string" }
      - { label: "Instituição", name: "instituicao", widget: "string" }
      - { label: "Período", name: "periodo", widget: "string", required: false }
      - { label: "Descrição", name: "body", widget: "markdown" }

  - name: "experiencias"
    label: "Experiências Profissionais"
    folder: "conteudo/experiencias"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Cargo", name: "cargo", widget: "string" }
      - { label: "Empresa", name: "empresa", widget: "string" }
      - { label: "Descrição", name: "body", widget: "markdown" }

  - name: "habilidades"
    label: "Habilidades"
    folder: "conteudo/habilidades"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "nome", widget: "string" }
      - { label: "Categoria", name: "categoria", widget: "string", required: false }
      - { label: "Descrição", name: "body", widget: "markdown", required: false }
